### PR TITLE
Atoms color fixes

### PR DESCRIPTION
**Pull request by Luthaf**
Fix #319 and some related code and layout cleanup.

@MaximeScope could you give this a look and check that everything works as intended?

### CODE REVIEW

**Comment by ceriottm** [comment]
Ghost environments are fixed, but the color scale remains even after switching to element coloring

**Comment by Luthaf** [comment]
> had some issue with the color scale remaining even after switching to element coloring, but might have been down to non-updated widgets

If you manage to reproduce let me know I'll try to fix it.

**Comment by Luthaf** [comment]
> when switching environments on and off and then on, it doesn't switch to environment highlighting until an atom is clicked on, IDK if that is intended or a bug

Should be fixed now

**Comment by ceriottm** [comment]
> > when switching environments on and off and then on, it doesn't switch to environment highlighting until an atom is clicked on, IDK if that is intended or a bug
> 
> Should be fixed now, we just go back to the previously selected center

Works.

**Comment by ceriottm** [comment]
fixed legend layout. @Luthaf  only thing I can't seem to manage to fix is the position of the modal, that at least on chrome seem to ignore completely what goes into positionsettingsrectangle

**Comment by ceriottm** [comment]
Fixed also the alignment I think

**Pull request merged**
