### PR TITLE
Post-release patches

### PR DESCRIPTION
**Pull request by ceriottm**
Solution courtesy of chatty

### CODE REVIEW

**Comment by ceriottm** [comment]
@Luthaf IDK if this needs also to do a new release, probably not given it only affects building from source.

**Comment by Luthaf** [comment]
The code was building fine for me without the changes (and is building fine on main), does it still fail for you if you clone a fresh main & run `npm ci`?

**Comment by ceriottm** [comment]
Ok it actually compiles from a clean clone. I see why it does that for the packages.json, not what triggers the typescript error. I'm closing this, we can return to this at a later stage, or at least include some info in Contributing.md about packages that should be pinned, and stuff that shouldn't be touched in packages.json

**Comment by Luthaf** [comment]
One of the updated depencency was the typescript compiler itself, so the old version did not understand the code anymore.

**Pull request closed without merging**
