### PR TITLE
Fix zoom issues

### PR DESCRIPTION
**Pull request by slietar**
Fix issues #12 and #141 as discussed with @Luthaf.

### CODE REVIEW

**Review by Luthaf — APPROVED** [review]
That looks very good, I'll merge once the CI is happy!

**Comment by Luthaf** [comment]
The Python test failure is unrelated to this PR, I'll fix it separately. I guess some float formatting code was updated and broke the tests.

The npm linting error is related to these changes though, you can run these tests with `npm test` to reproduce the error locally. You can use `// eslint-disable-next-line @typescript-eslint/no-explicit-any, @typescript-eslint/no-unsafe-member-access` on `(event as any).wheelDelta` to allow `any` on this specific line, and cast the result to a `number` for "Unsafe assignment of an `any` value".

**Comment by Luthaf** [comment]
You can rebase this branch on top of master to get the fix for the python tests (#211)

**Comment by Luthaf** [comment]
Merged! Thanks a lot @slietar

**Comment by slietar** [comment]
Cool! Thanks

**Pull request merged**
